### PR TITLE
Language

### PR DESCRIPTION
**Pull request by omitar**

### CODE REVIEW

**Comment by omitar** [comment]
I will squash at merge.

**Comment by nhynes** [comment]
@omitar you'll need to sign your commits

**Comment by omitar** [comment]
You just now added this requirement?

**Comment by nhynes** [comment]
No it's like that for all of our repos.

**Comment by omitar** [comment]
Hm. But this one is not signed? https://github.com/oasislabs/docs/commit/b6509e2516109e3ee7a2be9569cb57868d8d60d5

Oh, you already merged it? I didn't yet manage to sign them.

**Pull request merged**
