### PR TITLE
Improved language suggestion

### PR DESCRIPTION
**Pull request by jobravo**

### CODE REVIEW

**Comment by jobravo** [comment]
Oh, you have built stuff in the repo directly? No CI?

**Comment by nhynes** [comment]
> Oh, you have built stuff in the repo directly? No CI?

That would require giving CI write permissions to the repo, which is somewhat less than ideal. If you'd prefer not to install vuepress, I can build it on your behalf.

**Comment by jobravo** [comment]
Yes, if it is possible, could you please run the tool?

I think CI would be easier. You could also apply for: https://github.com/features/actions You are trusting GitHub anyway.

**Comment by jobravo** [comment]
So let me see if I get this right. I contributed fixes, somebody comes around, takes them as theirs, makes a new PR, and you merge that, while never attributing me in commits? Now I am not among contributors: https://github.com/oasislabs/docs/graphs/contributors

**Pull request closed without merging**
