### PR TITLE
operators: Reference consensus parameter update support in Staking docs

### PR DESCRIPTION
**Pull request by tjanez**
Follow-up from #207, needs to be vetted by legal.

### CODE REVIEW

**Comment by ravenac95** [comment]
Oh oops forgot about the legal component... that's my bad for approving...

**Comment by ctwardos** [comment]
where is the language for legal review here?

**Comment by pro-wh** [comment]
here it is: https://github.com/oasislabs/docs/pull/210/files#diff-b33d25d6a867e733b5b424d3a98527f1R317-R318

> Once updating consensus parameters is supported (tracked by
  [Oasis Core #2334]), this will no longer be the case.

"this" referring to the condition that gas costs cannot be changed

**Comment by tjanez** [comment]
@ctwardos, ping

**Pull request merged**
